/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedDataSourcesRouteImport } from './routes/_authed/data-sources'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedTokensRouteImport } from './routes/_authed/tokens'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as AuthedDashboardsIndexRouteImport } from './routes/_authed/dashboards.index'
import { Route as AuthedDashboardsDashboardIdRouteImport } from './routes/_authed/dashboards.$dashboardId'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiDashboardsIndexRouteImport } from './routes/api/dashboards.index'
import { Route as ApiDashboardsIdRouteImport } from './routes/api/dashboards.$id'
import { Route as ApiDataSourcesIndexRouteImport } from './routes/api/data-sources.index'
import { Route as ApiDataSourcesIdRouteImport } from './routes/api/data-sources.$id'
import { Route as ApiTokensIndexRouteImport } from './routes/api/tokens.index'
import { Route as ApiTokensIdRouteImport } from './routes/api/tokens.$id'
import { Route as ApiUsersMeRouteImport } from './routes/api/users/me'
import { Route as ApiDataSourcesIdConnectRouteImport } from './routes/api/data-sources.$id.connect'
import { Route as ApiDataSourcesIdQueryRouteImport } from './routes/api/data-sources.$id.query'
import { Route as ApiDataSourcesIdSchemaRouteImport } from './routes/api/data-sources.$id.schema'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDataSourcesRoute = AuthedDataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTokensRoute = AuthedTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardsIndexRoute = AuthedDashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardsDashboardIdRoute =
  AuthedDashboardsDashboardIdRouteImport.update({
    id: '/dashboards/$dashboardId',
    path: '/dashboards/$dashboardId',
    getParentRoute: () => AuthedRoute,
  } as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardsIndexRoute = ApiDashboardsIndexRouteImport.update({
  id: '/api/dashboards/',
  path: '/api/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardsIdRoute = ApiDashboardsIdRouteImport.update({
  id: '/api/dashboards/$id',
  path: '/api/dashboards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataSourcesIndexRoute = ApiDataSourcesIndexRouteImport.update({
  id: '/api/data-sources/',
  path: '/api/data-sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataSourcesIdRoute = ApiDataSourcesIdRouteImport.update({
  id: '/api/data-sources/$id',
  path: '/api/data-sources/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensIndexRoute = ApiTokensIndexRouteImport.update({
  id: '/api/tokens/',
  path: '/api/tokens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensIdRoute = ApiTokensIdRouteImport.update({
  id: '/api/tokens/$id',
  path: '/api/tokens/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersMeRoute = ApiUsersMeRouteImport.update({
  id: '/api/users/me',
  path: '/api/users/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataSourcesIdConnectRoute = ApiDataSourcesIdConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => ApiDataSourcesIdRoute,
} as any)
const ApiDataSourcesIdQueryRoute = ApiDataSourcesIdQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => ApiDataSourcesIdRoute,
} as any)
const ApiDataSourcesIdSchemaRoute = ApiDataSourcesIdSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => ApiDataSourcesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/data-sources': typeof AuthedDataSourcesRoute
  '/profile': typeof AuthedProfileRoute
  '/settings': typeof AuthedSettingsRoute
  '/tokens': typeof AuthedTokensRoute
  '/api/settings': typeof ApiSettingsRoute
  '/dashboards/$dashboardId': typeof AuthedDashboardsDashboardIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/dashboards/$id': typeof ApiDashboardsIdRoute
  '/api/data-sources/$id': typeof ApiDataSourcesIdRouteWithChildren
  '/api/tokens/$id': typeof ApiTokensIdRoute
  '/api/users/me': typeof ApiUsersMeRoute
  '/dashboards/': typeof AuthedDashboardsIndexRoute
  '/api/dashboards/': typeof ApiDashboardsIndexRoute
  '/api/data-sources/': typeof ApiDataSourcesIndexRoute
  '/api/tokens/': typeof ApiTokensIndexRoute
  '/api/data-sources/$id/connect': typeof ApiDataSourcesIdConnectRoute
  '/api/data-sources/$id/query': typeof ApiDataSourcesIdQueryRoute
  '/api/data-sources/$id/schema': typeof ApiDataSourcesIdSchemaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/data-sources': typeof AuthedDataSourcesRoute
  '/profile': typeof AuthedProfileRoute
  '/settings': typeof AuthedSettingsRoute
  '/tokens': typeof AuthedTokensRoute
  '/api/settings': typeof ApiSettingsRoute
  '/dashboards/$dashboardId': typeof AuthedDashboardsDashboardIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/dashboards/$id': typeof ApiDashboardsIdRoute
  '/api/data-sources/$id': typeof ApiDataSourcesIdRouteWithChildren
  '/api/tokens/$id': typeof ApiTokensIdRoute
  '/api/users/me': typeof ApiUsersMeRoute
  '/dashboards': typeof AuthedDashboardsIndexRoute
  '/api/dashboards': typeof ApiDashboardsIndexRoute
  '/api/data-sources': typeof ApiDataSourcesIndexRoute
  '/api/tokens': typeof ApiTokensIndexRoute
  '/api/data-sources/$id/connect': typeof ApiDataSourcesIdConnectRoute
  '/api/data-sources/$id/query': typeof ApiDataSourcesIdQueryRoute
  '/api/data-sources/$id/schema': typeof ApiDataSourcesIdSchemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/_authed/data-sources': typeof AuthedDataSourcesRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/tokens': typeof AuthedTokensRoute
  '/api/settings': typeof ApiSettingsRoute
  '/_authed/dashboards/$dashboardId': typeof AuthedDashboardsDashboardIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/dashboards/$id': typeof ApiDashboardsIdRoute
  '/api/data-sources/$id': typeof ApiDataSourcesIdRouteWithChildren
  '/api/tokens/$id': typeof ApiTokensIdRoute
  '/api/users/me': typeof ApiUsersMeRoute
  '/_authed/dashboards/': typeof AuthedDashboardsIndexRoute
  '/api/dashboards/': typeof ApiDashboardsIndexRoute
  '/api/data-sources/': typeof ApiDataSourcesIndexRoute
  '/api/tokens/': typeof ApiTokensIndexRoute
  '/api/data-sources/$id/connect': typeof ApiDataSourcesIdConnectRoute
  '/api/data-sources/$id/query': typeof ApiDataSourcesIdQueryRoute
  '/api/data-sources/$id/schema': typeof ApiDataSourcesIdSchemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/register'
    | '/data-sources'
    | '/profile'
    | '/settings'
    | '/tokens'
    | '/api/settings'
    | '/dashboards/$dashboardId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/dashboards/$id'
    | '/api/data-sources/$id'
    | '/api/tokens/$id'
    | '/api/users/me'
    | '/dashboards/'
    | '/api/dashboards/'
    | '/api/data-sources/'
    | '/api/tokens/'
    | '/api/data-sources/$id/connect'
    | '/api/data-sources/$id/query'
    | '/api/data-sources/$id/schema'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/register'
    | '/data-sources'
    | '/profile'
    | '/settings'
    | '/tokens'
    | '/api/settings'
    | '/dashboards/$dashboardId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/dashboards/$id'
    | '/api/data-sources/$id'
    | '/api/tokens/$id'
    | '/api/users/me'
    | '/dashboards'
    | '/api/dashboards'
    | '/api/data-sources'
    | '/api/tokens'
    | '/api/data-sources/$id/connect'
    | '/api/data-sources/$id/query'
    | '/api/data-sources/$id/schema'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/mcp'
    | '/register'
    | '/_authed/data-sources'
    | '/_authed/profile'
    | '/_authed/settings'
    | '/_authed/tokens'
    | '/api/settings'
    | '/_authed/dashboards/$dashboardId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/dashboards/$id'
    | '/api/data-sources/$id'
    | '/api/tokens/$id'
    | '/api/users/me'
    | '/_authed/dashboards/'
    | '/api/dashboards/'
    | '/api/data-sources/'
    | '/api/tokens/'
    | '/api/data-sources/$id/connect'
    | '/api/data-sources/$id/query'
    | '/api/data-sources/$id/schema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RegisterRoute: typeof RegisterRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiDashboardsIdRoute: typeof ApiDashboardsIdRoute
  ApiDataSourcesIdRoute: typeof ApiDataSourcesIdRouteWithChildren
  ApiTokensIdRoute: typeof ApiTokensIdRoute
  ApiUsersMeRoute: typeof ApiUsersMeRoute
  ApiDashboardsIndexRoute: typeof ApiDashboardsIndexRoute
  ApiDataSourcesIndexRoute: typeof ApiDataSourcesIndexRoute
  ApiTokensIndexRoute: typeof ApiTokensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/data-sources': {
      id: '/_authed/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof AuthedDataSourcesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tokens': {
      id: '/_authed/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof AuthedTokensRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboards/': {
      id: '/_authed/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof AuthedDashboardsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboards/$dashboardId': {
      id: '/_authed/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof AuthedDashboardsDashboardIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboards/': {
      id: '/api/dashboards/'
      path: '/api/dashboards'
      fullPath: '/api/dashboards/'
      preLoaderRoute: typeof ApiDashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboards/$id': {
      id: '/api/dashboards/$id'
      path: '/api/dashboards/$id'
      fullPath: '/api/dashboards/$id'
      preLoaderRoute: typeof ApiDashboardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data-sources/': {
      id: '/api/data-sources/'
      path: '/api/data-sources'
      fullPath: '/api/data-sources/'
      preLoaderRoute: typeof ApiDataSourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data-sources/$id': {
      id: '/api/data-sources/$id'
      path: '/api/data-sources/$id'
      fullPath: '/api/data-sources/$id'
      preLoaderRoute: typeof ApiDataSourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens/': {
      id: '/api/tokens/'
      path: '/api/tokens'
      fullPath: '/api/tokens/'
      preLoaderRoute: typeof ApiTokensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens/$id': {
      id: '/api/tokens/$id'
      path: '/api/tokens/$id'
      fullPath: '/api/tokens/$id'
      preLoaderRoute: typeof ApiTokensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/me': {
      id: '/api/users/me'
      path: '/api/users/me'
      fullPath: '/api/users/me'
      preLoaderRoute: typeof ApiUsersMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data-sources/$id/connect': {
      id: '/api/data-sources/$id/connect'
      path: '/connect'
      fullPath: '/api/data-sources/$id/connect'
      preLoaderRoute: typeof ApiDataSourcesIdConnectRouteImport
      parentRoute: typeof ApiDataSourcesIdRoute
    }
    '/api/data-sources/$id/query': {
      id: '/api/data-sources/$id/query'
      path: '/query'
      fullPath: '/api/data-sources/$id/query'
      preLoaderRoute: typeof ApiDataSourcesIdQueryRouteImport
      parentRoute: typeof ApiDataSourcesIdRoute
    }
    '/api/data-sources/$id/schema': {
      id: '/api/data-sources/$id/schema'
      path: '/schema'
      fullPath: '/api/data-sources/$id/schema'
      preLoaderRoute: typeof ApiDataSourcesIdSchemaRouteImport
      parentRoute: typeof ApiDataSourcesIdRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDataSourcesRoute: typeof AuthedDataSourcesRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTokensRoute: typeof AuthedTokensRoute
  AuthedDashboardsDashboardIdRoute: typeof AuthedDashboardsDashboardIdRoute
  AuthedDashboardsIndexRoute: typeof AuthedDashboardsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDataSourcesRoute: AuthedDataSourcesRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTokensRoute: AuthedTokensRoute,
  AuthedDashboardsDashboardIdRoute: AuthedDashboardsDashboardIdRoute,
  AuthedDashboardsIndexRoute: AuthedDashboardsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiDataSourcesIdRouteChildren {
  ApiDataSourcesIdConnectRoute: typeof ApiDataSourcesIdConnectRoute
  ApiDataSourcesIdQueryRoute: typeof ApiDataSourcesIdQueryRoute
  ApiDataSourcesIdSchemaRoute: typeof ApiDataSourcesIdSchemaRoute
}

const ApiDataSourcesIdRouteChildren: ApiDataSourcesIdRouteChildren = {
  ApiDataSourcesIdConnectRoute: ApiDataSourcesIdConnectRoute,
  ApiDataSourcesIdQueryRoute: ApiDataSourcesIdQueryRoute,
  ApiDataSourcesIdSchemaRoute: ApiDataSourcesIdSchemaRoute,
}

const ApiDataSourcesIdRouteWithChildren =
  ApiDataSourcesIdRoute._addFileChildren(ApiDataSourcesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RegisterRoute: RegisterRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiDashboardsIdRoute: ApiDashboardsIdRoute,
  ApiDataSourcesIdRoute: ApiDataSourcesIdRouteWithChildren,
  ApiTokensIdRoute: ApiTokensIdRoute,
  ApiUsersMeRoute: ApiUsersMeRoute,
  ApiDashboardsIndexRoute: ApiDashboardsIndexRoute,
  ApiDataSourcesIndexRoute: ApiDataSourcesIndexRoute,
  ApiTokensIndexRoute: ApiTokensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
